create-manifest:
  name: Create Manifest and Push
  needs: [build-amd64, build-arm64]
  runs-on: ubuntu-24.04
  permissions:
    id-token: write
    contents: read
    packages: write
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Create and push manifest - testing
      if: ${{ !github.event.release }}
      run: |
        docker manifest create cookielab/unit-php:${{ github.ref_name }} \
          cookielab/unit-php:${{ github.ref_name }}-amd64 \
          cookielab/unit-php:${{ github.ref_name }}-arm64
        docker manifest push cookielab/unit-php:${{ github.ref_name }}
        docker manifest create public.ecr.aws/cookielab/unit-php:${{ github.ref_name }} \
          public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}-amd64 \
          public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}-arm64
        docker manifest push public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}
        docker manifest create ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}-amd64 \
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}-arm64
        docker manifest push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    - name: Create and push manifest - pre-release
      if: ${{ github.event.release && github.event.release.prerelease == true }}
      run: |
        docker manifest create cookielab/unit-php:${{ github.event.release.tag_name }} \
          cookielab/unit-php:${{ github.event.release.tag_name }}-amd64 \
          cookielab/unit-php:${{ github.event.release.tag_name }}-arm64
        docker manifest push cookielab/unit-php:${{ github.event.release.tag_name }}
        docker manifest create public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }} \
          public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-amd64 \
          public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-arm64
        docker manifest push public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}
        docker manifest create ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
          ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-amd64 \
          ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-arm64
        docker manifest push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

    - name: Create and push manifest - stable
      if: ${{ github.event.release && github.event.release.prerelease == false }}
      run: |
        docker manifest create cookielab/unit-php:${{ github.event.release.tag_name }} \
          cookielab/unit-php:${{ github.event.release.tag_name }}-amd64 \
          cookielab/unit-php:${{ github.event.release.tag_name }}-arm64
        docker manifest push cookielab/unit-php:${{ github.event.release.tag_name }}
        docker manifest create public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }} \
          public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-amd64 \
          public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-arm64
        docker manifest push public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}
        docker manifest create ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
          ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-amd64 \
          ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-arm64
        docker manifest push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
