name: Container Image

on:
  push:
    branches:
      - main
      - multi-arch
    tags: "**"

env:
  php_version: 8.4.2
  unit_version: 1.34.0
  composer_version: 2.8.4
  datadog_version: 1.5.1
  xdebug_version: 3.4.0

jobs:
  build-amd64:
    name: Build amd64 Image
    runs-on: ubuntu-latest
    timeout-minutes: 190
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build and push - testing
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.ref_name }}-amd64

      - name: Build and push - pre-release
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-amd64

      - name: Build and push - stable
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-amd64

      - name: Build and push - testing - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=${{ github.ref_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.ref_name }}-dd-amd64

      - name: Build and push - pre-release - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-dd-amd64

      - name: Build and push - stable - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-dd-amd64

  build-arm64:
    name: Build arm64 Image
    runs-on: [ubuntu-latest, arm64]
    timeout-minutes: 190
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build and push - testing
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.ref_name }}-arm64

      - name: Build and push - pre-release
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-arm64

      - name: Build and push - stable
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          build-args: |
            PHP_VERSION=${{ env.php_version }}
            UNIT_VERSION=${{ env.unit_version }}
            COMPOSER_VERSION=${{ env.composer_version }}
            XDEBUG_VERSION=${{ env.xdebug_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-arm64

      - name: Build and push - testing - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/arm64
          push: false
          build-args: |
            VERSION=${{ github.ref_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.ref_name }}-dd-arm64

      - name: Build and push - pre-release - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/arm64
          push: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-dd-arm64

      - name: Build and push - stable - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/arm64
          push: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            DATADOG_VERSION=${{ env.datadog_version }}
          tags: cookielab/unit-php:${{ github.event.release.tag_name }}-dd-arm64

  create-manifest:
    name: Create Manifest and Push
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and push - testing
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.ref_name }}
            public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Build and push - pre-release
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.event.release.tag_name }}
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

      - name: Build and push - stable
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.event.release.tag_name }}
            cookielab/unit-php:${{ github.event.release.tag_name }}
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

      - name: Build and push - testing - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ !github.event.release }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.ref_name }}-dd
            public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}-dd
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-dd
            cookielab/unit-php:${{ github.ref_name }}-datadog
            public.ecr.aws/cookielab/unit-php:${{ github.ref_name }}-datadog
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-datadog

      - name: Build and push - pre-release - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == true }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-dd
            cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-datadog

      - name: Build and push - stable - Datadog
        uses: docker/build-push-action@v6
        timeout-minutes: 180
        if: ${{ github.event.release && github.event.release.prerelease == false }}
        with:
          context: .
          file: ./Dockerfile.datadog
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-dd
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-dd
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-dd
            cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            public.ecr.aws/cookielab/unit-php:${{ github.event.release.tag_name }}-datadog
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-datadog
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}-datadog
